// Generated by https://quicktype.io

export interface BerriesResponse {
  count:    number;
  next:     string;
  previous: null;
  results:  Berry[];
}

export interface Berry {
  name: string;
  url:  string;
}
